# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 谷雨实验室
title: 面向个人和中小企业的技术咨询，软件开发，数据分析，编程辅导
email: huji624@qq.com
phone: huji624(添加请备注谷雨)
website: guyu.biz

# Social links
twitter_username: jekyllrb
github_username:  jekyll
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
xing_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
googleplus_username: +jekyll

# About Section
about_title: 关于我们
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
    - Lists
    - Tables
    - Links
    - Images

# Projects Section
projects_title: 成员简介

# Experience Section
experience_title: 业务范围

# Education Section
education_title: 合作单位

# More Section
more_title: 最后
more_content: | # this will include new lines to allow paragraphs
  我们都曾经在一线城市打拼，最近纷纷回到重庆，感叹重庆的互联网企业之少，和一些传统企业的老板
  聊天的过程中发现，传统企业也有很多需要用互联网思维，用计算机技术来解决的痛点，但这些中小企业主本身都是公司的中流
  砥柱，日常非常繁忙，并没有那么多的时间和精力去学习和理解互联网技术到底能带来什么，应该怎么一步一步去实施。

  与此同时重庆的互联网人才相对也非常匮乏，我在招聘网站上看到有相当多的传统企业或者小型公司都在招聘互联网人才，有的
  职位已经发布了数月都没有招到合适的人，这就造成了一个死循环，没有相应的互联网企业吸引不到相应的人才，进而更发展不
  出相应的企业。

  成立这个工作室的目的，一方面我们希望能帮助这些企业和个人解决问题，另一方面也希望能探索一条适合在二三线城市发展的互联网企业之路。

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-cayman