# Product Template
- layout: left
  pic: http://static.luckyhu.top:8824/youling.jpg
  quote: >
    适合上班族的盯盘软件 - 幽灵股票
  description: | # this will include new lines to allow paragraphs
    项目详情：<a href="https://luckyhu.top/gs">点这里</a>

- layout: left
  pic: https://guyu.biz/hextris/images/twitter-opengraph.png
  quote: >
    轻松小游戏，简单易上手 - 六边俄罗斯
  description: | # this will include new lines to allow paragraphs
    去试试：<a href="https://guyu.biz/hextris/">点这里</a>